# Generated by Django 5.0.7 on 2025-02-15 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الموازنة')),
                ('description', models.TextField(verbose_name='وصف الموازنة')),
                ('status', models.CharField(choices=[('فعلية', 'فعلية'), ('تقديرية', 'تقديرية')], max_length=50, verbose_name='حالة الموازنة')),
                ('date', models.DateField(unique=True, verbose_name='تاريخ الموازنة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'موازنة',
                'verbose_name_plural': 'الموازنات',
            },
        ),
        migrations.CreateModel(
            name='ClientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, unique=True, verbose_name='فئة العميل')),
            ],
            options={
                'verbose_name': 'فئة العميل',
                'verbose_name_plural': 'فئات العملاء',
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, unique=True, verbose_name='نوع العميل')),
            ],
            options={
                'verbose_name': 'نوع العميل',
                'verbose_name_plural': 'انواع العملاء',
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Covenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('covenant_owner', models.CharField(default='', max_length=100, verbose_name='صاحب العهد')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قيمة العهد')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ المدفوع')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المتبقي')),
                ('note', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاريخ العهد')),
            ],
            options={
                'verbose_name': 'عهد',
                'verbose_name_plural': 'العهود',
            },
        ),
        migrations.CreateModel(
            name='CovenantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, unique=True, verbose_name='شكل العهد')),
            ],
            options={
                'verbose_name': 'شكل العهد',
                'verbose_name_plural': 'اشكال العهد',
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, unique=True, verbose_name='فئة المصروف')),
            ],
            options={
                'verbose_name': 'فئة المصروف',
                'verbose_name_plural': 'فئات المصروفات',
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_owner', models.CharField(default='', max_length=100, verbose_name='صاحب السلف')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قيمة السلف')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ المدفوع')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='المتبقي')),
                ('note', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاريخ السلفة')),
            ],
            options={
                'verbose_name': 'سلفة',
                'verbose_name_plural': 'السلف',
            },
        ),
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, unique=True, verbose_name='شكل السلف')),
            ],
            options={
                'verbose_name': 'شكل السلف',
                'verbose_name_plural': 'اشكال السلف',
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='RevenueCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, unique=True, verbose_name='فئة الايراد')),
            ],
            options={
                'verbose_name': 'فئة الايراد',
                'verbose_name_plural': 'فئات الايرادات',
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='BudgetUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.budget')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': [],
                'unique_together': {('budget', 'user')},
            },
        ),
        migrations.AddField(
            model_name='budget',
            name='users',
            field=models.ManyToManyField(related_name='budgets', through='core.BudgetUsers', to=settings.AUTH_USER_MODEL, verbose_name='المستخدمون الذين يمكنهم العمل على الموازنة'),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم العميل')),
                ('image', models.ImageField(blank=True, null=True, upload_to='clients/images/', verbose_name='صورة العميل')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الرصيد')),
                ('join_date', models.DateField(verbose_name='تاريخ الانضمام')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.clientcategory', verbose_name='فئة العميل')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.clienttype', verbose_name='نوع العميل')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
            },
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='عنوان المستند')),
                ('file', models.FileField(upload_to='documents/', verbose_name='الملف')),
                ('date_upload', models.DateField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.client', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'مستند',
                'verbose_name_plural': 'المستندات',
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='ClientEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='عنوان البريد الإلكتروني')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='core.client', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'عنوان البريد الإلكتروني',
                'verbose_name_plural': 'عناوين البريد الإلكتروني',
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='ClientPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='رقم الهاتف')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='core.client', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'رقم الهاتف',
                'verbose_name_plural': 'أرقام الهواتف',
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='CovenantHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='القيمة')),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المدفوع')),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المتبقي')),
                ('note', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التعديل')),
                ('covenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.covenant', verbose_name='العهدة')),
            ],
            options={
                'verbose_name': 'سجل العهدة',
                'verbose_name_plural': 'سجلات العهد',
                'default_permissions': [],
            },
        ),
        migrations.AddField(
            model_name='covenant',
            name='covenant_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covenants', to='core.covenanttype', verbose_name='شكل العهد'),
        ),
        migrations.CreateModel(
            name='BudgetExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='بيان المصروف')),
                ('estimated_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ التقديري')),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='المبلغ الفعلي')),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='المبلغ المدفوع')),
                ('remaining_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='المتبقي')),
                ('date', models.DateField(verbose_name='تاريخ المصروف')),
                ('expense_status', models.CharField(choices=[('urgent', 'عاجل'), ('important', 'مهم'), ('normal', 'عادي')], default='normal', max_length=10, verbose_name='حالة المصروف')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.budget', verbose_name='الموازنة')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_expense_categorys', to='core.expensecategory', verbose_name='فئة المصروف')),
            ],
            options={
                'verbose_name': 'مصروف موازنة',
                'verbose_name_plural': 'مصروفات الموازنة',
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الصندوق')),
                ('description', models.TextField(verbose_name='وصف الصندوق')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الرصيد الافتتاحي')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الرصيد الحالي')),
                ('date', models.DateField(verbose_name='تاريخ الصندوق')),
                ('is_private', models.BooleanField(default=False, verbose_name='صندوق خاص')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='صاحب الصندوق')),
            ],
            options={
                'verbose_name': 'صندوق',
                'verbose_name_plural': 'الصناديق',
                'permissions': [('viewall_funds', 'عرض كل الصناديق'), ('viewprivate_funds', 'عرض الصناديق الخاصة')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='FundExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='بيان المصروف')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ')),
                ('date', models.DateField(verbose_name='تاريخ المصروف')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_expense_categorys', to='core.expensecategory', verbose_name='فئة المصروف')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fund', verbose_name='الصندوق')),
            ],
            options={
                'verbose_name': 'مصروف صندوق',
                'verbose_name_plural': 'مصروفات الصندوق',
            },
        ),
        migrations.CreateModel(
            name='LoanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='القيمة')),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المدفوع')),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المتبقي')),
                ('note', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التعديل')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.loan', verbose_name='السلفة')),
            ],
            options={
                'verbose_name': 'سجل السلفة',
                'verbose_name_plural': 'سجلات السلف',
                'default_permissions': [],
            },
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='core.loantype', verbose_name='شكل السلف'),
        ),
        migrations.CreateModel(
            name='FundRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='بيان الإيراد')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ')),
                ('date', models.DateField(verbose_name='تاريخ الإيراد')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fund', verbose_name='الصندوق')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_revenue_categorys', to='core.revenuecategory', verbose_name='فئة الايراد')),
            ],
            options={
                'verbose_name': 'إيراد صندوق',
                'verbose_name_plural': 'إيرادات الصندوق',
            },
        ),
        migrations.CreateModel(
            name='BudgetRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='بيان الإيراد')),
                ('estimated_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ التقديري')),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='المبلغ الفعلي')),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='المبلغ المدفوع')),
                ('remaining_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='المتبقي')),
                ('date', models.DateField(verbose_name='تاريخ الإيراد')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.budget', verbose_name='الموازنة')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_revenues', to='core.client', verbose_name='العميل')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_revenue_categorys', to='core.revenuecategory', verbose_name='فئة الايراد')),
            ],
            options={
                'verbose_name': 'إيراد موازنة',
                'verbose_name_plural': 'إيرادات الموازنة',
            },
        ),
    ]
