# Generated by Django 5.0.7 on 2025-01-21 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الموازنة')),
                ('description', models.TextField(verbose_name='وصف الموازنة')),
                ('status', models.CharField(choices=[('فعلية', 'فعلية'), ('تقديرية', 'تقديرية')], max_length=50, verbose_name='حالة الموازنة')),
                ('date', models.DateField(unique=True, verbose_name='تاريخ الموازنة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'موازنة',
                'verbose_name_plural': 'الموازنات',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم العميل')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='رقم الهاتف')),
                ('type', models.CharField(max_length=50, verbose_name='النوع')),
                ('category', models.CharField(max_length=50, verbose_name='الفئة')),
                ('join_date', models.DateField(verbose_name='تاريخ الانضمام')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الرصيد')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
            },
        ),
        migrations.CreateModel(
            name='BudgetExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='فئة المصروف')),
                ('description', models.TextField(verbose_name='وصف المصروف')),
                ('estimated_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ التقديري')),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='المبلغ الفعلي')),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='المبلغ المدفوع')),
                ('remaining_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='المتبقي')),
                ('date', models.DateField(verbose_name='تاريخ المصروف')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.budget', verbose_name='الموازنة')),
            ],
            options={
                'verbose_name': 'مصروف موازنة',
                'verbose_name_plural': 'مصروفات الموازنة',
            },
        ),
        migrations.CreateModel(
            name='BudgetRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='فئة الإيراد')),
                ('description', models.TextField(verbose_name='وصف إضافي للإيراد')),
                ('estimated_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ التقديري')),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='المبلغ الفعلي')),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='المبلغ المدفوع')),
                ('remaining_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='المتبقي')),
                ('date', models.DateField(verbose_name='تاريخ عملية الإيراد')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.budget', verbose_name='الموازنة')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'إيراد موازنة',
                'verbose_name_plural': 'إيرادات الموازنة',
            },
        ),
        migrations.CreateModel(
            name='Covenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('covenant_type', models.CharField(max_length=100, verbose_name='شكل العهد')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قيمة العهد')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ المدفوع')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المتبقي')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='صاحب العهد')),
            ],
            options={
                'verbose_name': 'عهدة',
                'verbose_name_plural': 'العهود',
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الصندوق')),
                ('description', models.TextField(verbose_name='وصف الصندوق')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الرصيد الافتتاحي')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الرصيد الحالي')),
                ('date', models.DateField(verbose_name='تاريخ الصندوق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='صاحب الصندوق')),
            ],
            options={
                'verbose_name': 'صندوق',
                'verbose_name_plural': 'الصناديق',
            },
        ),
        migrations.CreateModel(
            name='FundExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ')),
                ('category', models.CharField(max_length=100, verbose_name='فئة المصروف')),
                ('description', models.TextField(verbose_name='وصف المصروف')),
                ('date', models.DateField(verbose_name='تاريخ المصروف')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fund', verbose_name='الصندوق')),
            ],
            options={
                'verbose_name': 'مصروف صندوق',
                'verbose_name_plural': 'مصروفات الصندوق',
            },
        ),
        migrations.CreateModel(
            name='FundRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ')),
                ('category', models.CharField(max_length=100, verbose_name='فئة الإيراد')),
                ('description', models.TextField(verbose_name='وصف الإيراد')),
                ('date', models.DateField(verbose_name='تاريخ الإيراد')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fund', verbose_name='الصندوق')),
            ],
            options={
                'verbose_name': 'إيراد صندوق',
                'verbose_name_plural': 'إيرادات الصندوق',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(max_length=100, verbose_name='شكل السلف')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قيمة السلف')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ المدفوع')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='المتبقي')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='صاحب السلف')),
            ],
            options={
                'verbose_name': 'سلفة',
                'verbose_name_plural': 'السلف',
            },
        ),
    ]
