# Generated by Django 5.0.7 on 2025-02-05 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='core.loantype', verbose_name='شكل السلفس'),
        ),
    ]
