# Generated by Django 5.0.7 on 2025-01-31 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='covenant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='user',
        ),
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.ImageField(null=True, upload_to='clients/images/', verbose_name='صورة العميل'),
        ),
        migrations.AddField(
            model_name='covenant',
            name='covenant_owner',
            field=models.CharField(default='owner', max_length=100, verbose_name='صاحب العهدة'),
        ),
        migrations.AddField(
            model_name='covenant',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_owner',
            field=models.CharField(default='owner', max_length=100, verbose_name='صاحب السلف'),
        ),
        migrations.AddField(
            model_name='loan',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='budgetexpense',
            name='description',
            field=models.CharField(max_length=100, verbose_name='بيان المصروف'),
        ),
        migrations.AlterField(
            model_name='budgetrevenue',
            name='description',
            field=models.CharField(max_length=100, verbose_name='بيان الإيراد'),
        ),
        migrations.AlterField(
            model_name='client',
            name='category',
            field=models.CharField(max_length=50, verbose_name='فئة العميل'),
        ),
        migrations.AlterField(
            model_name='client',
            name='type',
            field=models.CharField(max_length=50, verbose_name='نوع العميل'),
        ),
        migrations.AlterField(
            model_name='covenant',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قيمة العهدة'),
        ),
        migrations.AlterField(
            model_name='covenant',
            name='covenant_type',
            field=models.CharField(max_length=100, verbose_name='شكل العهدة'),
        ),
        migrations.AlterField(
            model_name='covenant',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='تاريخ العهدة'),
        ),
        migrations.AlterField(
            model_name='fundexpense',
            name='description',
            field=models.CharField(max_length=100, verbose_name='بيان المصروف'),
        ),
        migrations.AlterField(
            model_name='fundrevenue',
            name='description',
            field=models.CharField(max_length=100, verbose_name='بيان الإيراد'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='تاريخ السلفة'),
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='عنوان المستند')),
                ('file', models.FileField(upload_to='documents/', verbose_name='الملف')),
                ('date_upload', models.DateField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.client', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'مستند',
                'verbose_name_plural': 'المستندات',
            },
        ),
        migrations.CreateModel(
            name='ClientEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20, unique=True, verbose_name='عنوان البريد الإلكتروني')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='core.client', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'عنوان البريد الإلكتروني',
                'verbose_name_plural': 'عناوين البريد الإلكتروني',
            },
        ),
        migrations.CreateModel(
            name='ClientPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='رقم الهاتف')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='core.client', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'رقم الهاتف',
                'verbose_name_plural': 'أرقام الهواتف',
            },
        ),
        migrations.CreateModel(
            name='CovenantHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='القيمة')),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المدفوع')),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المتبقي')),
                ('note', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التعديل')),
                ('covenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.covenant', verbose_name='العهدة')),
            ],
            options={
                'verbose_name': 'سجل العهدة',
                'verbose_name_plural': 'سجلات العهد',
            },
        ),
        migrations.CreateModel(
            name='LoanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='القيمة')),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المدفوع')),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المتبقي')),
                ('note', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التعديل')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.loan', verbose_name='السلفة')),
            ],
            options={
                'verbose_name': 'سجل السلفة',
                'verbose_name_plural': 'سجلات السلف',
            },
        ),
    ]
