# Generated by Django 5.0.7 on 2025-02-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_client_email_remove_client_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clients/images/', verbose_name='صورة العميل'),
        ),
    ]
