# Generated by Django 5.0.7 on 2025-02-05 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_loan_loan_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='covenant',
            options={'verbose_name': 'عهد', 'verbose_name_plural': 'العهود'},
        ),
        migrations.AlterField(
            model_name='budgetexpense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_expense_categorys', to='core.expensecategory', verbose_name='فئة المصروف'),
        ),
        migrations.AlterField(
            model_name='budgetrevenue',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_revenue_categorys', to='core.revenuecategory', verbose_name='فئة الايراد'),
        ),
        migrations.AlterField(
            model_name='client',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.clientcategory', verbose_name='فئة العميل'),
        ),
        migrations.AlterField(
            model_name='client',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.clienttype', verbose_name='نوع العميل'),
        ),
        migrations.AlterField(
            model_name='covenant',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قيمة العهد'),
        ),
        migrations.AlterField(
            model_name='covenant',
            name='covenant_owner',
            field=models.CharField(default='owner', max_length=100, verbose_name='صاحب العهد'),
        ),
        migrations.AlterField(
            model_name='covenant',
            name='covenant_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covenants', to='core.covenanttype', verbose_name='شكل العهد'),
        ),
        migrations.AlterField(
            model_name='covenant',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='تاريخ العهد'),
        ),
        migrations.AlterField(
            model_name='fundexpense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_expense_categorys', to='core.expensecategory', verbose_name='فئة المصروف'),
        ),
        migrations.AlterField(
            model_name='fundrevenue',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_revenue_categorys', to='core.revenuecategory', verbose_name='فئة الايراد'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='core.loantype', verbose_name='شكل السلف'),
        ),
    ]
