# Generated by Django 5.0.7 on 2025-02-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_covenant_options_alter_budgetexpense_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covenant',
            name='covenant_owner',
            field=models.CharField(default='', max_length=100, verbose_name='صاحب العهد'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_owner',
            field=models.CharField(default='', max_length=100, verbose_name='صاحب السلف'),
        ),
    ]
