# Generated by Django 5.0.7 on 2025-02-02 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_client_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetrevenue',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_revenues', to='core.client', verbose_name='العميل'),
        ),
    ]
