# Generated by Django 5.0.7 on 2025-02-03 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_budgetrevenue_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fund',
            options={'permissions': [('view_all_funds', 'Can view all funds')], 'verbose_name': 'صندوق', 'verbose_name_plural': 'الصناديق'},
        ),
    ]
