# Generated by Django 5.0.7 on 2025-02-03 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_fund_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='covenanthistory',
            options={'permissions': [], 'verbose_name': 'سجل العهدة', 'verbose_name_plural': 'سجلات العهد'},
        ),
        migrations.AlterModelOptions(
            name='fund',
            options={'permissions': [('viewall_funds', 'عرض كل الصناديق'), ('viewprivate_funds', 'عرض الصنادي الخاصة')], 'verbose_name': 'صندوق', 'verbose_name_plural': 'الصناديق'},
        ),
    ]
