# Generated by Django 5.0.7 on 2025-02-03 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_covenanthistory_options_alter_fund_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientdocument',
            options={'default_permissions': [], 'verbose_name': 'مستند', 'verbose_name_plural': 'المستندات'},
        ),
        migrations.AlterModelOptions(
            name='clientemail',
            options={'default_permissions': [], 'verbose_name': 'عنوان البريد الإلكتروني', 'verbose_name_plural': 'عناوين البريد الإلكتروني'},
        ),
        migrations.AlterModelOptions(
            name='clientphone',
            options={'default_permissions': [], 'verbose_name': 'رقم الهاتف', 'verbose_name_plural': 'أرقام الهواتف'},
        ),
        migrations.AlterModelOptions(
            name='covenanthistory',
            options={'default_permissions': [], 'verbose_name': 'سجل العهدة', 'verbose_name_plural': 'سجلات العهد'},
        ),
        migrations.AlterModelOptions(
            name='fund',
            options={'permissions': [('viewall_funds', 'عرض كل الصناديق'), ('viewprivate_funds', 'عرض الصناديق الخاصة')], 'verbose_name': 'صندوق', 'verbose_name_plural': 'الصناديق'},
        ),
        migrations.AlterModelOptions(
            name='loanhistory',
            options={'default_permissions': [], 'verbose_name': 'سجل السلفة', 'verbose_name_plural': 'سجلات السلف'},
        ),
    ]
