# Generated by Django 5.0.7 on 2025-02-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_clientdocument_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='صندوق خاص'),
        ),
    ]
