# Generated by Django 5.0.7 on 2025-02-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_fund_is_private'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetexpense',
            options={'default_permissions': [], 'verbose_name': 'مصروف موازنة', 'verbose_name_plural': 'مصروفات الموازنة'},
        ),
        migrations.AlterModelOptions(
            name='budgetrevenue',
            options={'default_permissions': [], 'verbose_name': 'إيراد موازنة', 'verbose_name_plural': 'إيرادات الموازنة'},
        ),
        migrations.AlterModelOptions(
            name='fundexpense',
            options={'default_permissions': [], 'verbose_name': 'مصروف صندوق', 'verbose_name_plural': 'مصروفات الصندوق'},
        ),
        migrations.AlterModelOptions(
            name='fundrevenue',
            options={'default_permissions': [], 'verbose_name': 'إيراد صندوق', 'verbose_name_plural': 'إيرادات الصندوق'},
        ),
        migrations.AddField(
            model_name='budgetexpense',
            name='expense_status',
            field=models.CharField(choices=[('urgent', 'عاجل'), ('important', 'مهم'), ('normal', 'عادي')], default='normal', max_length=10, verbose_name='حالة المصروف'),
        ),
    ]
