# Generated by Django 5.0.7 on 2025-02-03 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_budgetexpense_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fund',
            options={'permissions': [('viewall_funds', 'عرض كل الصناديق'), ('viewprivate_funds', 'عرضلصناديق الخاصة')], 'verbose_name': 'صندوق', 'verbose_name_plural': 'الصناديق'},
        ),
    ]
