# Generated by Django 5.0.7 on 2025-02-03 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_fund_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fund',
            options={'permissions': [('viewall_funds', 'عرض كل الصناديق'), ('viewprivate_funds', 'عرض الصناديق الخاصة')], 'verbose_name': 'صندوق', 'verbose_name_plural': 'الصناديق'},
        ),
    ]
